# Generated by Django 6.0.4 on 2026-05-21 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad_paquete', models.PositiveIntegerField(default=1, help_text='Cuántas unidades trae el paquete (ej: 20, 100, 500)')),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='EscalaPrecios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_escala', models.CharField(help_text='Ej: Unidad, Media docena, Docena, Media caja, Caja', max_length=100)),
                ('cantidad_minima', models.PositiveIntegerField(help_text='Cantidad mínima para aplicar este precio')),
                ('cantidad_maxima', models.PositiveIntegerField(blank=True, help_text='Cantidad máxima (dejar vacío si no hay límite)', null=True)),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio por unidad individual en esta escala', max_digits=10)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, help_text='% de descuento sobre precio base por unidad', max_digits=5)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Escala de Precios',
                'verbose_name_plural': 'Escalas de Precios',
                'ordering': ['producto', 'cantidad_minima'],
            },
        ),
    ]
