# Generated by Django 6.0.4 on 2026-05-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código o referencia del producto', max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='impuesto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='% de impuesto (IVA)', max_digits=5),
        ),
    ]
